/**
 * Example usage of Edge WAF Rulesmith API
 * This demonstrates how to use the API programmatically
 */

const WORKER_URL = 'https://edge-waf-rulesmith.your-subdomain.workers.dev';

// Example 1: Generate a WAF rule from natural language
async function generateRule() {
  const response = await fetch(`${WORKER_URL}/api/chat`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      message: 'block SQL injections on /login endpoint',
      sessionId: null,
      history: [],
    }),
  });

  const data = await response.json();
  console.log('Generated Rule:', data.rule);
  return data;
}

// Example 2: Validate a WAF expression
async function validateRule(expression) {
  const response = await fetch(`${WORKER_URL}/api/rules/preview`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ expression }),
  });

  const data = await response.json();
  console.log('Validation Result:', data);
  return data;
}

// Example 3: Apply a rule to Cloudflare
async function applyRule(zoneId, expression, action = 'block', description = '') {
  const response = await fetch(`${WORKER_URL}/api/rules`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      zone_id: zoneId,
      expression,
      action,
      description: description || 'Generated by Edge WAF Rulesmith',
      enabled: true,
    }),
  });

  const data = await response.json();
  console.log('Apply Result:', data);
  return data;
}

// Example 4: List existing rules
async function listRules(zoneId) {
  const response = await fetch(`${WORKER_URL}/api/rules?zone_id=${zoneId}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  const data = await response.json();
  console.log('Existing Rules:', data);
  return data;
}

// Example 5: Complete workflow
async function completeWorkflow() {
  try {
    // Step 1: Generate rule
    console.log('Step 1: Generating rule...');
    const generation = await generateRule();
    const expression = generation.rule.rule;

    // Step 2: Validate
    console.log('\nStep 2: Validating rule...');
    const validation = await validateRule(expression);
    
    if (!validation.valid) {
      console.error('Validation failed:', validation.errors);
      return;
    }

    // Step 3: Apply (uncomment and set zoneId to actually deploy)
    // console.log('\nStep 3: Applying rule...');
    // const zoneId = 'your-zone-id-here';
    // await applyRule(zoneId, expression, generation.rule.action, generation.rule.description);

    console.log('\nWorkflow complete!');
  } catch (error) {
    console.error('Error:', error);
  }
}

// Run example
if (require.main === module) {
  completeWorkflow();
}

module.exports = {
  generateRule,
  validateRule,
  applyRule,
  listRules,
  completeWorkflow,
};

